# Generated by Django 4.2.4 on 2023-08-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques_app', '0001_initial'),
        ('consultas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Banco',
        ),
        migrations.DeleteModel(
            name='Cheque',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cheques_app.cheque',),
        ),
    ]
